# Generated by Django 3.0.3 on 2021-04-16 22:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catDescripcion', models.CharField(max_length=100, verbose_name='CategoriaDescripcion')),
                ('catEstado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodDescripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('prodImagen', models.ImageField(blank=True, null=True, upload_to='producto')),
                ('prodImagen2', models.ImageField(blank=True, null=True, upload_to='producto2')),
                ('prodCantidad', models.IntegerField(blank=True, default=0, null=True)),
                ('prodPrecio', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('prodTotal', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True)),
                ('prodIva', models.DecimalField(decimal_places=2, default=0.12, max_digits=10)),
                ('prodCaracteristica', models.TextField(blank=True, max_length=400, null=True)),
                ('prodEstprod', models.IntegerField(blank=True, default=1)),
                ('prodTipo', models.IntegerField(blank=True, default=2)),
                ('prodEstado', models.BooleanField(default=True, verbose_name='Estado')),
                ('usuaReg', models.IntegerField(blank=True, null=True)),
                ('usuaMod', models.IntegerField(blank=True, null=True)),
                ('usuaEli', models.IntegerField(blank=True, null=True)),
                ('prodFecReg', models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 16, 17, 22, 43, 344411), null=True)),
                ('prodFecMod', models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 16, 17, 22, 43, 344411), null=True)),
                ('prodFecEli', models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 16, 17, 22, 43, 344411), null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto.Categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodcFecElab', models.DateTimeField(default=datetime.datetime(2021, 4, 16, 17, 22, 43, 346360))),
                ('prodcCantidad', models.IntegerField(default=1)),
                ('prodcTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('prodcEstado', models.BooleanField(default=True, verbose_name='Estado')),
                ('prodcTipo', models.IntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto.Producto')),
            ],
            options={
                'verbose_name': 'Produccion',
                'verbose_name_plural': 'Producciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GastosAdicionales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gastdescripcion', models.CharField(max_length=100)),
                ('gastprecio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto.Producto')),
            ],
            options={
                'verbose_name': 'Detalle Gastos Adicional',
                'verbose_name_plural': 'Detalle Gastos Adicionales',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detprecio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('detCantidad', models.IntegerField(default=1)),
                ('detSubtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insumo.Insumo')),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto.Produccion')),
            ],
            options={
                'verbose_name': 'Detalle de Producto',
                'verbose_name_plural': 'Detalle de Productos',
                'ordering': ['id'],
            },
        ),
    ]
