# Generated by Django 3.0.3 on 2020-10-15 21:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='prodTalla',
        ),
        migrations.AddField(
            model_name='detproducto',
            name='detSubtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detproducto',
            name='detprecio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='prodCaracteristica',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='prodEstprod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='prodTotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='detproducto',
            name='detcantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecElab',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 15, 16, 11, 7, 954887)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecEli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 15, 16, 11, 7, 954887), null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecMod',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 15, 16, 11, 7, 954887), null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecReg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 15, 16, 11, 7, 954887), null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodTipo',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='GastosAdicionales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gastdescripcion', models.CharField(max_length=100)),
                ('gastprecio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto.Producto')),
            ],
            options={
                'verbose_name': 'Detalle Gastos Adicional',
                'verbose_name_plural': 'Detalle Gastos Adicionales',
                'ordering': ['id'],
            },
        ),
    ]
