# Generated by Django 3.0.3 on 2020-11-16 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='prodFecElab',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 16, 14, 42, 0, 808376)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecEli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 16, 14, 42, 0, 808376), null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecMod',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 16, 14, 42, 0, 808376), null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecReg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 16, 14, 42, 0, 808376), null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodIva',
            field=models.DecimalField(decimal_places=2, default=0.12, max_digits=10),
        ),
    ]
