# Generated by Django 3.0.3 on 2020-10-16 02:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20201015_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detproducto',
            name='detcantidad',
        ),
        migrations.AddField(
            model_name='detproducto',
            name='detCantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecElab',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 15, 21, 44, 54, 260597)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecEli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 15, 21, 44, 54, 261594), null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecMod',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 15, 21, 44, 54, 261594), null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecReg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 15, 21, 44, 54, 261594), null=True),
        ),
    ]
