# Generated by Django 3.0.3 on 2020-12-10 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20201208_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='prodCaracteristica',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecElab',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 10, 16, 4, 52, 21456)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecEli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 10, 16, 4, 52, 21456), null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecMod',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 10, 16, 4, 52, 21456), null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecReg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 10, 16, 4, 52, 21456), null=True),
        ),
    ]
