# Generated by Django 3.0.3 on 2020-10-17 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20201015_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='prodFecElab',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 16, 22, 14, 35, 445557)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecEli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 16, 22, 14, 35, 445557), null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecMod',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 16, 22, 14, 35, 445557), null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecReg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 16, 22, 14, 35, 445557), null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodImagen',
            field=models.ImageField(blank=True, null=True, upload_to='producto/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodImagen2',
            field=models.ImageField(blank=True, null=True, upload_to='producto2/'),
        ),
    ]
