# Generated by Django 3.0.3 on 2021-01-24 03:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_auto_20210123_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='prodFecElab',
        ),
        migrations.AlterField(
            model_name='produccion',
            name='prodcFecElab',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 22, 27, 53, 888962)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecEli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 23, 22, 27, 53, 887986), null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecMod',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 23, 22, 27, 53, 887986), null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecReg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 23, 22, 27, 53, 887986), null=True),
        ),
    ]
