# Generated by Django 3.0.3 on 2020-10-17 03:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_auto_20201016_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='prodFecElab',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 16, 22, 26, 50, 250852)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecEli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 16, 22, 26, 50, 250852), null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecMod',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 16, 22, 26, 50, 250852), null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecReg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 16, 22, 26, 50, 250852), null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodImagen',
            field=models.ImageField(blank=True, null=True, upload_to='producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodImagen2',
            field=models.ImageField(blank=True, null=True, upload_to='producto2'),
        ),
    ]
