# Generated by Django 3.0.3 on 2021-01-24 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_auto_20210123_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='prodcFecElab',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 22, 43, 47, 356772)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodEstprod',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecEli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 23, 22, 43, 47, 355798), null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecMod',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 23, 22, 43, 47, 355798), null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecReg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 23, 22, 43, 47, 355798), null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodTipo',
            field=models.IntegerField(blank=True, default=2),
        ),
    ]
