# Generated by Django 3.0.3 on 2021-02-18 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_auto_20210123_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produccion',
            options={'ordering': ['id'], 'verbose_name': 'Produccion', 'verbose_name_plural': 'Producciones'},
        ),
        migrations.AlterField(
            model_name='produccion',
            name='prodcFecElab',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 14, 31, 57, 618290)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecEli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 18, 14, 31, 57, 617311), null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecMod',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 18, 14, 31, 57, 617311), null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecReg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 18, 14, 31, 57, 617311), null=True),
        ),
    ]
