# Generated by Django 3.0.3 on 2021-02-18 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0011_auto_20210218_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='prodcFecElab',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 18, 2, 52, 284166)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecEli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 18, 18, 2, 52, 283190), null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecMod',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 18, 18, 2, 52, 283190), null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecReg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 18, 18, 2, 52, 283190), null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodPrecio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
