# Generated by Django 3.0.3 on 2021-03-31 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0014_auto_20210331_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='catEstado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='prodcFecElab',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 17, 19, 24, 61181)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecEli',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 31, 17, 19, 24, 60207), null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecMod',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 31, 17, 19, 24, 60207), null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prodFecReg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 31, 17, 19, 24, 60207), null=True),
        ),
    ]
