# Generated by Django 3.0.3 on 2021-04-29 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0022_auto_20210429_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='prodcFecElab',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 16, 43, 57, 2627)),
        ),
    ]
