# Generated by Django 3.0.3 on 2021-05-03 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0023_auto_20210429_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='prodcFecElab',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 9, 15, 7, 896972)),
        ),
    ]
