# Generated by Django 3.0.3 on 2021-05-04 02:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0025_auto_20210503_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='prodcFecElab',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 21, 4, 59, 21637)),
        ),
    ]
