# Generated by Django 3.0.3 on 2021-04-08 16:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20210218_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contratoDescripcion', models.CharField(blank=True, max_length=150, verbose_name='Nombre')),
                ('contratoFec_Inicio', models.DateTimeField(default=datetime.datetime.now)),
                ('contratoFec_Fin', models.DateTimeField(default=datetime.datetime.now)),
                ('contratoEstado', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.Cliente')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['id'],
            },
        ),
    ]
