# Generated by Django 3.0.3 on 2021-06-15 14:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CabCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('ccoFecCom', models.DateField(default=datetime.datetime.now)),
                ('ccoVendedor', models.CharField(max_length=50, verbose_name='Vendedor')),
                ('ccoCedVend', models.CharField(max_length=13, verbose_name='Cedula')),
                ('ccoSubtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ccoIva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ccoTotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ccoEstado', models.BooleanField(default=True, verbose_name='Estado')),
                ('ccoDocumento', models.FileField(blank=True, null=True, upload_to='documento/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Cabecera Compra',
                'verbose_name_plural': 'Cabecera Compras',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcoPreCom', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dcoCantidad', models.IntegerField(default=0)),
                ('dcoSubtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cabCompra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compra.CabCompra')),
            ],
            options={
                'verbose_name': 'Detalle Compra',
                'verbose_name_plural': 'Detalle Compras',
                'ordering': ['id'],
            },
        ),
    ]
