# Generated by Django 3.0.3 on 2021-04-16 22:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedor', '0001_initial'),
        ('insumo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccoFecCom', models.DateField(default=datetime.datetime.now)),
                ('ccoVendedor', models.CharField(max_length=50, verbose_name='Vendedor')),
                ('ccoCedVend', models.CharField(max_length=13, verbose_name='Cedula')),
                ('ccoSubtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ccoIva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ccoTotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ccoEstado', models.BooleanField(default=True, verbose_name='Estado')),
                ('ccoDocumento', models.FileField(blank=True, null=True, upload_to='documento/%Y/%m/%d')),
                ('usuaReg', models.IntegerField(blank=True, null=True)),
                ('usuaMod', models.IntegerField(blank=True, null=True)),
                ('usuaEli', models.IntegerField(blank=True, null=True)),
                ('ccoFecReg', models.DateTimeField(default=datetime.datetime(2021, 4, 16, 17, 22, 43, 340506))),
                ('ccoFecMod', models.DateTimeField(default=datetime.datetime(2021, 4, 16, 17, 22, 43, 340506))),
                ('ccoFecEli', models.DateTimeField(default=datetime.datetime(2021, 4, 16, 17, 22, 43, 340506))),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedor.Proveedor')),
            ],
            options={
                'verbose_name': 'Cabecera Compra',
                'verbose_name_plural': 'Cabecera Compras',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcoPreCom', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dcoCantidad', models.IntegerField(default=0)),
                ('dcoSubtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cabCompra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compra.CabCompra')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insumo.Insumo')),
            ],
            options={
                'verbose_name': 'Detalle Compra',
                'verbose_name_plural': 'Detalle Compras',
                'ordering': ['id'],
            },
        ),
    ]
