# Generated by Django 3.0.3 on 2021-05-06 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumo', '0001_initial'),
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detcompra',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insumo.Insumo'),
        ),
    ]
