# Generated by Django 3.0.3 on 2021-06-15 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compra', '0003_cabcompra_proveedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cabcompra',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compra_cabcompra_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cabcompra',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compra_cabcompra_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
