# Generated by Django 3.0.3 on 2020-11-24 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0005_auto_20201124_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabcompra',
            name='ccoDocumento',
            field=models.FileField(blank=True, null=True, upload_to='documento/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='cabcompra',
            name='ccoFecCom',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 24, 16, 29, 2, 634882)),
        ),
        migrations.AlterField(
            model_name='cabcompra',
            name='ccoFecEli',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 24, 16, 29, 2, 634882)),
        ),
        migrations.AlterField(
            model_name='cabcompra',
            name='ccoFecMod',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 24, 16, 29, 2, 634882)),
        ),
        migrations.AlterField(
            model_name='cabcompra',
            name='ccoFecReg',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 24, 16, 29, 2, 634882)),
        ),
    ]
