# Generated by Django 3.0.3 on 2021-04-27 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0005_auto_20210419_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabcompra',
            name='ccoFecEli',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 12, 51, 5, 761876)),
        ),
        migrations.AlterField(
            model_name='cabcompra',
            name='ccoFecMod',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 12, 51, 5, 761876)),
        ),
        migrations.AlterField(
            model_name='cabcompra',
            name='ccoFecReg',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 12, 51, 5, 761876)),
        ),
    ]
