# Generated by Django 3.0.3 on 2021-02-18 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0010_auto_20210218_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabcompra',
            name='ccoCedVend',
            field=models.CharField(max_length=13, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='cabcompra',
            name='ccoFecCom',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 17, 58, 29, 238688)),
        ),
        migrations.AlterField(
            model_name='cabcompra',
            name='ccoFecEli',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 17, 58, 29, 238688)),
        ),
        migrations.AlterField(
            model_name='cabcompra',
            name='ccoFecMod',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 17, 58, 29, 238688)),
        ),
        migrations.AlterField(
            model_name='cabcompra',
            name='ccoFecReg',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 17, 58, 29, 238688)),
        ),
    ]
