# Generated by Django 3.0.3 on 2021-04-29 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compra', '0020_auto_20210429_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabcompra',
            name='ccoFecEli',
        ),
        migrations.RemoveField(
            model_name='cabcompra',
            name='ccoFecMod',
        ),
        migrations.RemoveField(
            model_name='cabcompra',
            name='ccoFecReg',
        ),
        migrations.RemoveField(
            model_name='cabcompra',
            name='usuaEli',
        ),
        migrations.RemoveField(
            model_name='cabcompra',
            name='usuaMod',
        ),
        migrations.RemoveField(
            model_name='cabcompra',
            name='usuaReg',
        ),
        migrations.AddField(
            model_name='cabcompra',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cabcompra',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='cabcompra',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compra_cabcompra_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cabcompra',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compra_cabcompra_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
