# Generated by Django 3.0.3 on 2021-05-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('catDescripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('catEstado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('insCod', models.CharField(max_length=100)),
                ('insDescripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('insModelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('insPrecio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('insIva', models.DecimalField(decimal_places=2, default=0.12, max_digits=10)),
                ('insImagen', models.ImageField(blank=True, null=True, upload_to='fotos/%Y/%m/%d')),
                ('insStock', models.IntegerField(blank=True, default=0, null=True, verbose_name='Stock')),
                ('insEstado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UnidadMedidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('medDescripcion', models.CharField(max_length=50, verbose_name='Medidad')),
                ('medEstado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Medida',
                'verbose_name_plural': 'Medidas',
                'ordering': ['id'],
            },
        ),
    ]
