# Generated by Django 3.0.3 on 2021-06-15 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insumo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadmedidad',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insumo_unidadmedidad_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unidadmedidad',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insumo_unidadmedidad_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insumo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insumo.Categoria'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insumo.UnidadMedidad'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insumo_insumo_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insumo',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insumo_insumo_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoria',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insumo_categoria_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoria',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insumo_categoria_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
