# Generated by Django 3.0.3 on 2020-10-12 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='insIva',
        ),
    ]
