# Generated by Django 3.0.3 on 2020-10-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0002_remove_insumo_insiva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='insStock',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Stock'),
        ),
    ]
