# Generated by Django 3.0.3 on 2020-11-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0003_auto_20201012_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='insPrecio',
            field=models.DecimalField(decimal_places=2, default=1.25, max_digits=10),
        ),
    ]
