# Generated by Django 3.0.3 on 2020-11-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0004_auto_20201102_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='insCod',
            field=models.CharField(max_length=100),
        ),
    ]
