# Generated by Django 3.0.3 on 2021-04-29 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insumo', '0004_auto_20210429_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadmedidad',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='unidadmedidad',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='unidadmedidad',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insumo_unidadmedidad_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unidadmedidad',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insumo_unidadmedidad_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
