# Generated by Django 3.0.3 on 2021-05-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0005_auto_20210429_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='insIva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
