# Generated by Django 3.0.3 on 2021-04-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulogrupo',
            name='icono',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
