# Generated by Django 3.0.3 on 2021-05-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulogrupo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
