# Generated by Django 3.0.3 on 2020-12-03 20:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ventnum', models.CharField(max_length=20)),
                ('venFechaInici', models.DateTimeField(default=datetime.datetime(2020, 12, 3, 15, 24, 12, 190875))),
                ('venFechaFin', models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 3, 15, 24, 12, 190875), null=True)),
                ('ventObservacion', models.CharField(max_length=100)),
                ('venTipo', models.CharField(choices=[('1', 'Contrato'), ('2', 'Normal')], default='2', max_length=20)),
                ('venEstVenta', models.CharField(choices=[('1', 'Pendiente'), ('2', 'Pagado')], default='2', max_length=20)),
                ('ventTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('ventSubtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('ventImpuesto', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('ventEstado', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.Cliente')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GastAdc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gastdescripcion', models.CharField(max_length=100)),
                ('gastprecio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venta.Venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalle de Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detPrecio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('detCant', models.IntegerField(default=1)),
                ('detSubtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto.Producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venta.Venta')),
            ],
        ),
    ]
