# Generated by Django 3.0.3 on 2020-10-21 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0006_auto_20201020_1958'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ventnum', models.CharField(max_length=20)),
                ('venFechaInici', models.DateTimeField()),
                ('venFechaFin', models.DateTimeField()),
                ('ventObservacion', models.CharField(max_length=100)),
                ('venTipo', models.CharField(choices=[('1', 'Contrato'), ('2', 'Normal')], default='1', max_length=20)),
                ('ventTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('ventEstado', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='GastAdc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gastdescripcion', models.CharField(max_length=100)),
                ('gastprecio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venta.Venta')),
            ],
        ),
        migrations.CreateModel(
            name='DetVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detCant', models.IntegerField(default=1)),
                ('detSubtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto.Producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venta.Venta')),
            ],
        ),
    ]
