# Generated by Django 3.0.3 on 2021-04-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='ventDescuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
