# Generated by Django 3.0.3 on 2020-12-08 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_auto_20201208_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='venEstVenta',
            field=models.CharField(choices=[('1', 'Pendiente'), ('2', 'Pagado')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='venFechaFin',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 8, 16, 47, 5, 425948), null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='venFechaInici',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 8, 16, 47, 5, 425948)),
        ),
    ]
