# Generated by Django 3.0.3 on 2021-04-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_venta_ventdescuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='ventTotalDescuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
