# Generated by Django 3.0.3 on 2020-12-10 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_auto_20201208_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='venFechaFin',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 10, 16, 4, 52, 25480), null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='venFechaInici',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 10, 16, 4, 52, 25480)),
        ),
    ]
