# Generated by Django 3.0.3 on 2021-04-19 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_venta_venttotaldescuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='ventTotalDescuento',
        ),
    ]
