# Generated by Django 3.0.3 on 2021-01-24 03:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_auto_20210123_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='venFechaFin',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 23, 22, 27, 53, 892866), null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='venFechaInici',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 22, 27, 53, 892866)),
        ),
    ]
