# Generated by Django 3.0.3 on 2020-11-02 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_auto_20201102_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='venFechaFin',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 2, 17, 37, 48, 683088), null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='venFechaInici',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 17, 37, 48, 683088)),
        ),
    ]
