# Generated by Django 3.0.3 on 2020-12-02 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0006_auto_20201124_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='venEstVenta',
            field=models.CharField(choices=[('1', 'Pendiente'), ('2', 'Pagado')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='venFechaFin',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 2, 11, 17, 11, 68207), null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='venFechaInici',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 11, 17, 11, 68207)),
        ),
    ]
