# Generated by Django 3.0.3 on 2020-12-02 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0007_auto_20201202_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='venFechaFin',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 2, 11, 44, 16, 747739), null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='venFechaInici',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 11, 44, 16, 747739)),
        ),
        migrations.AlterField(
            model_name='venta',
            name='venTipo',
            field=models.CharField(choices=[('1', 'Contrato'), ('2', 'Normal')], default='2', max_length=20),
        ),
    ]
