# Generated by Django 3.0.3 on 2020-12-02 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0008_auto_20201202_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='venEstVenta',
            field=models.CharField(choices=[('1', 'Pendiente'), ('2', 'Pagado')], default='2', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='venFechaFin',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 2, 15, 6, 30, 520778), null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='venFechaInici',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 15, 6, 30, 520778)),
        ),
    ]
