# Generated by Django 3.0.3 on 2021-02-18 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0012_auto_20210218_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='venFechaFin',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 18, 18, 59, 16, 417339), null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='venFechaInici',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 18, 59, 16, 417339)),
        ),
    ]
