# Generated by Django 3.0.3 on 2021-04-06 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0016_auto_20210331_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='venFechaFin',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 6, 15, 40, 8, 769694), null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='venFechaInici',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 15, 40, 8, 769694)),
        ),
    ]
