# Generated by Django 3.0.3 on 2021-06-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emprNombre', models.CharField(blank=True, max_length=150, verbose_name='Nombre')),
                ('emprRuc', models.CharField(max_length=13, unique=True, verbose_name='Ruc')),
                ('emprEmail', models.EmailField(blank=True, max_length=50, verbose_name='Email')),
                ('emprTelefono', models.CharField(blank=True, max_length=25, verbose_name='Telefono')),
                ('emprDireccion', models.CharField(blank=True, max_length=100, verbose_name='Direccion')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['id'],
            },
        ),
    ]
